### ISSUE TITLE
Logger has not been set!

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/magento-v1-extractor#1]
Fungující konfigurace přestala náhle fungovat

https://connection.keboola.com/admin/projects/837/jobs?q=magento

https://connection.keboola.com/admin/utils/logs?file=2018/06/21/02/2018-06-21-02-09-56-5b2aecd43c752-log
https://connection.keboola.com/admin/utils/logs?file=2018/06/21/02/2018-06-21-02-09-56-5b2aecd437454-exception

```
Logger has not been set!
#0 /code/vendor/keboola/extractor-bundle/Extractor/Jobs/RestJob.php(54): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#1 /code/vendor/keboola/magento-extractor-bundle/Keboola/MagentoExtractorBundle/MagentoExtractorJob.php(57): Keboola\ExtractorBundle\Extractor\Jobs\RestJob->download(Object(GuzzleHttp\Message\Request))
#2 /code/vendor/keboola/magento-extractor-bundle/Keboola/MagentoExtractorBundle/MagentoExtractor.php(84): Keboola\MagentoExtractorBundle\MagentoExtractorJob->run()
#3 /code/src/Keboola/MagentoExtractor/RunCommand.php(59): Keboola\MagentoExtractorBundle\MagentoExtractor->run(Object(Keboola\ExtractorBundle\Config\Config))
#4 /code/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(253): Keboola\MagentoExtractor\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /code/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(889): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /code/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Keboola\MagentoExtractor\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /code/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /code/src/run.php(16): Symfony\Component\Console\Application->run(NULL, Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}
```

Tipuju, že asi chce něco vypsat do logu a v ten okamžik chybí logger?

**Comment by JakubMatejka** [comment]
Zatím vidím, že to failuje tady: https://bitbucket.org/keboola/extractor-bundle/src/befce85767bdee0a0949a5c40263ec505e0ec346/Extractor/Jobs/RestJob.php#lines-54 Takže to vypadá, že se nenastavil logger Guzzlu (což mi teda přijde trochu divný, protože povinný to není) a ten se vytváří tady: https://github.com/keboola/magento-extractor-bundle/blob/master/MagentoExtractor.php#L54

**Comment by ondrejhlavacek** [comment]
Sakra, jsem brouzdal na bitbucketu v masteru a tam to bylo o pár řádek mimo.

**Comment by JakubMatejka** [comment]
Jj. Nezdálo se mi to, tak jsem šel do packagistu než mi došlo, že je to v
branchi ;o)

**Comment by ondrejhlavacek** [comment]
Tady minimalistická failující konfigurace - https://connection.keboola.com/admin/projects/837/extractors/keboola.ex-magento-v1/408066047
Můžem to na ní pouštět - šlo by třeba pouštět custom tag a na tom to debugovat.

**Comment by JakubMatejka** [comment]
Hm, tady odtud ta chyba nejspíš vyplavala: https://bitbucket.org/keboola/extractor-bundle/src/cb2259ce2ab3ee2f30b9206f0ed3a21a2ef16837/Common/Logger.php?at=master#Logger.php-44 takže by snad mohlo stačit todle: https://github.com/keboola/magento-v1-extractor/pull/2/files#diff-7b0a2cc2a15b0bffc740b594dee65940R44

**Comment by JakubMatejka** [comment]
Běží to už půl hodiny: https://connection.keboola.com/admin/projects/837/jobs/408109991

**Comment by ondrejhlavacek** [comment]
Sleduju to! :-)

**Comment by ondrejhlavacek** [comment]
Doběhlo, jdu jim říct, ať to pustí celý, vypadá to na fix, díky!

**Comment by JakubMatejka** [comment]
👍
